version: "3.9"


services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DB
    env_file:
    - .env

  app:
    build:
      context: .
      target: development
    command: |
      sh web.entrypoint.sh
    ports:
    - "8000:8000"
    env_file:
    - .env
    depends_on:
    - mongodb